### ISSUE TITLE
Log warning on every analytics bulk POST

### ISSUE THREAD

**Issue by mrdon-reciprocity** [launchdarkly/python-server-sdk#124] opened 2019-05-30 20:10 UTC
Seemingly every time the library sends bulk analytic data back, the following error is logged as a warning:

Unhandled exception in event processor. Analytics events were not processed. ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

It doesn't seem to affect either the performance of the library or even the analytics as viewed in the Launchdarkly web UI.  

It seems to have started on May 21st, which doesn't correspond to any library upgrades on our side.  We are running the latest 6.9.2

**Comment by bwoskow-ld** [comment] 2019-05-30 20:38
Hi Mr. Don!

Thanks for the report. We'll take a look at our deployment history from that timeframe and see if anything related lines up.

Ben

**Comment by bwoskow-ld** [comment] 2019-06-03 21:32
Hey Mr. Don,

The engineering team can't reproduce this error using version 6.9.2 of the Python SDK against LaunchDarkly's staging or production environments. However, based on the error logged, this likely means that your outbound stream connection (from your app to LaunchDarkly) is closing unexpectedly, potentially failing to flush analytics events. The SDK's retry logic is such that, in case events fail to be processed/sent, the SDK will retry one additional time before permanently dropping the events. As a result, even though you say that this issue doesn't affect analytics as viewed in the LaunchDarkly web UI, it very well might be the case that the web UI only shows a subset of your actual event analytics and that the remainder is never being sent.

At this point I recommend reaching out to our support team at support@launchdarkly.com to investigate further and on a private channel. Although you didn't deploy any corresponding library upgrades in during this timeframe, there might be configuration changes or rollout changes which may be related.

Cheers,
Ben

**Closed by bwoskow-ld** 2019-06-03 21:32 UTC

**Comment by mrdon-reciprocity** [comment] 2019-06-04 23:48
k, I'll keep looking on my side.  Thanks for looking it Ben, and good to see you still around :)

**Comment by dgoade55** [comment] 2020-03-26 20:51
were you able to get this fixed? i think I have the same problem.

**Comment by eli-darkly** [comment] 2020-03-26 21:13
@dgoade55 It's a very general symptom that just indicates some kind of network problem, so it's unlikely that this old report is the same as your case. I recommend contacting LaunchDarkly support; they may be able to help investigate further.

**Comment by dgoade55** [comment] 2020-03-26 22:10
thanks -- will do
